In [2]:
import numpy as np

In [3]:
# NumPy Arrays
array1 = np.array([1, 2, 3, 4, 5, 6])

list = [1, 2, 3, 4, 5, 6]
array2 = np.array(list) # equivalent ways of making arrays

print(array1)
print(array2)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [4]:
# Creating arrays from imported data
# If we have a csv, we can create arrays from this data by using np.genfromtxt
# The first argument is the name of the file
# Delimiter tells us how the values are separated, i.e. by comma or spaces
import os
os.getcwd()
os.chdir("/Users/majalie/Desktop/LSESU CODESOC")
cylinders = np.genfromtxt('Auto.csv', delimiter=',')

In [11]:
# Operations with Numpy arrays

# Method 1: Lists
l = [1, 2, 3, 4, 5]
for i in range(len(l)):
    l[i] = l[i] + 3
    
print(l)

# Method 2: Arrays
a = np.array(l)
a = a + 3
print(a)

# Note how the array code is much shorter

# Addition and Subtraction of Arrays
# Arrays must be the same length
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])
total_grade = test_1 + test_2 + test_3
total_grade

[4, 5, 6, 7, 8]
[ 7  8  9 10 11]


array([258, 279, 246, 274, 270])

In [12]:
# Two-Dimensional Arrays: arrays containing arrays of the same size
# Often used to represent a set of samples in statistics
test_grades = np.array([test_1, test_2, test_3])
test_grades = np.array([[92, 94, 88, 91, 87], 
                        [79, 100, 86, 93, 91], 
                        [87, 85, 72, 90, 92]])
# If we're writing out the arrays inside, we need to make sure to enclose them with []

In [13]:
# Selecting Elements: one-dimensional arrays
test_1[0]
test_1[0:3]

# Selecting Elements: two-dimensional arrays
# Use two indices
print(test_grades[2, 1]) # selects element in the third row, second column
print(test_grades[:,1]) # selects all of the second column
print(test_grades[0,:]) # selects all of the first row

85
[ 94 100  85]
[92 94 88 91 87]


In [14]:
# Logical Operations with arrays
# Element-wise
array = np.array([10, 2, 0, 4, 5, 6, 9, 8])
array > 5

array([ True, False, False, False, False,  True,  True,  True])

In [15]:
# Select elements that are FALSE
array[array < 5]

array([2, 0, 4])

In [16]:
# Combine logical operators to make complex statements using "OR" and "AND"
array[(array > 5) & (array < 10)]
array[(array > 5) | (array < 2)]

array([10,  0,  6,  9,  8])

In [17]:
# Summary Statistics with NumPy
# Mean of one-dimensional array
np.mean(test_1)

#Mean of two-dimensional arrays
overall_mean = np.mean(test_grades)
row_means = np.mean(test_grades, axis = 1) # axis 1 is rows
column_means = np.mean(test_grades, axis = 0) # axis 0 is columns

print(overall_mean)
print(row_means)
print(column_means)

# Mean and logical statements
passed = np.mean(test_1 > 50) # calculates the percent/ratio of how many test scores are above 50
print(passed)

# Outliers - visualize what your outliers are by using sort to rearrange the data in your array
np.sort(test_2)

# Percentiles
# First argument is array, second argument is percentile
np.percentile(test_1, 10)

# Median
np.median([1, 2, 4, 5, 5, 6, 7])

# Standard deviation
np.std(test_1)
print(np.std(test_1))

88.46666666666667
[90.4 89.8 85.2]
[86.         93.         82.         91.33333333 90.        ]
1.0
2.576819745345025
