In [3]:
# Exercise 1: Write a NumPy program to reverse an array

import numpy as np

def reverse_array():
    x = np.array(list(map(int, input().split()))) # this piece of code splits the input string into individual values, then maps each value to an integer type and stores it in a list. We make an array from this list
    x = x[::-1] # reverses the array
    print(x)
    
reverse_array()

1 2 3 4
[4 3 2 1]


In [8]:
# Exercise 2: Write a NumPy program to convert Celsius to Fahreheit given an array of values in Celsius

def fahrenheit():
    x = np.array(list(map(int, input().split())))
    f = (9/5)*x + 32
    print(f)

fahrenheit()

0 100
[ 32. 212.]


In [11]:
# Exercise 3: Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

def common():
    array1 = np.array(list(map(int, input().split())))
    array2 = np.array(list(map(int, input().split())))
    print(np.in1d(array1, array2)) # another method in NumPy that checks if the elements in a 1D array are in the second array
    
common()

1 2 3 4
2 4 6 8
[False  True False  True]


In [18]:
# Exercise 4: Write a NumPy program to find the union of two arrays

def union():
    array1 = np.array(list(map(int, input().split())))
    array2 = np.array(list(map(int, input().split())))
    print(np.union1d(array1, array2))

union()

1 2 3
2 3 4
[1 2 3 4]


In [17]:
# Exercise 5: Write a NumPy program to change the data type of an array

array = np.array(list(map(int, input().split())))
print("Data type of original array is: ", array.dtype)
new_array = array.astype(float)
print("New array type: ", new_array.dtype)
print(new_array)

1 2 3 4
Data type of original array is:  int64
New array type:  float64
[1. 2. 3. 4.]


In [27]:
# Exercise 6: Write a NumPy program to read a CSV data file and store records in an array

import os 
os.getcwd()
os.chdir('/Users/majalie/Desktop/LSESU CODESOC')

import pandas as pd

Auto = pd.read_csv("Auto.csv")
Auto.head()
cylinders = Auto.loc[:,"cylinders"]
cylinders_array = np.array(cylinders)
print(cylinders_array)

[8 8 8 8 8 8 8 8 8 8 8 8 8 8 4 6 6 6 4 4 4 4 4 4 6 8 8 8 8 4 4 4 4 6 6 6 6
 6 8 8 8 8 8 8 8 6 4 6 6 4 4 4 4 4 4 4 4 4 4 4 4 4 8 8 8 8 8 8 8 8 8 3 8 8
 8 8 4 4 4 4 4 4 4 4 4 8 8 8 8 8 8 8 8 8 8 8 8 6 6 6 6 6 4 8 8 8 8 6 4 4 4
 3 4 6 4 8 8 4 4 4 4 8 4 6 8 6 6 6 6 4 4 4 4 6 6 6 8 8 8 8 8 4 4 4 4 4 4 4
 4 4 4 4 6 6 6 6 8 8 8 8 6 6 6 6 6 8 8 4 4 6 4 4 4 4 6 4 6 4 4 4 4 4 4 4 4
 4 4 8 8 8 8 6 6 6 6 4 4 4 4 6 6 6 6 4 4 4 4 4 8 4 6 6 8 8 8 8 4 4 4 4 4 8
 8 8 8 6 6 6 6 8 8 8 8 4 4 4 4 4 4 4 4 6 4 3 4 4 4 4 4 8 8 8 6 6 6 4 6 6 6
 6 6 6 8 6 8 8 4 4 4 4 4 4 4 4 5 6 4 6 4 4 6 6 4 6 6 8 8 8 8 8 8 8 8 4 4 4
 4 5 8 4 8 4 4 4 4 4 6 6 4 4 4 4 4 4 4 4 6 4 4 4 4 4 4 4 4 4 4 5 4 4 4 4 4
 6 3 4 4 4 4 4 4 6 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 6 6 6 6 8 6 6 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 6 6 4 6 4 4 4 4 4 4 4 4]
